# Generated by Django 5.0.14 on 2025-05-24 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empeños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEmpeño', models.DateField(verbose_name='Fecha de Empeño')),
                ('PlazoMeses', models.IntegerField(default=4, editable=False, verbose_name='Plazo mes')),
                ('InteresMensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='interes por MES')),
                ('Estado', models.CharField(choices=[('A', 'activo'), ('R', 'recuperado'), ('P', 'perdido')], default='A', max_length=1, verbose_name='estado del empeño')),
                ('fk_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'empeño',
                'verbose_name_plural': 'empeños',
            },
        ),
    ]
