# Generated by Django 5.0.14 on 2025-05-24 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empeños', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendasPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPerdida', models.DateField(verbose_name='Fecha de empeño')),
                ('Fk_empeño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empeños.empeños')),
            ],
            options={
                'verbose_name': 'Prendas Perdida',
                'verbose_name_plural': 'Prendas Perdidas',
            },
        ),
    ]
