# Generated by Django 5.0.14 on 2025-05-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendasPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPerdida', models.DateField(auto_now=True, verbose_name='Fecha de empeño')),
                ('Fk_empeño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'PrendasPerdida',
                'verbose_name_plural': 'PrendasPerdidas',
            },
        ),
    ]
