# Generated by Django 5.0.14 on 2025-05-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrendasPerdidas', '0001_initial'),
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prendasperdidas',
            options={'verbose_name': 'Prenda Perdida', 'verbose_name_plural': 'Prendas Perdidas'},
        ),
        migrations.AddField(
            model_name='prendasperdidas',
            name='fk_prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prendas.prendas'),
        ),
    ]
