# Generated by Django 5.0.14 on 2025-05-22 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empeños', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del abono')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('tipoabono', models.CharField(choices=[('I', 'interes'), ('C', 'capital')], default='I', max_length=1)),
                ('fk_empeño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empeños.empeños')),
            ],
            options={
                'verbose_name': 'abono',
                'verbose_name_plural': 'abonos',
            },
        ),
    ]
