# Generated by Django 5.0.14 on 2025-05-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PesoGramos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='peso de prenda gramos')),
                ('ValorEstimado', models.FloatField(verbose_name='valor estimado')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='descripcion de la joya')),
                ('fk_clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'prenda',
                'verbose_name_plural': 'prendas',
            },
        ),
    ]
